# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: mattforge/python-fibonacci-actions

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  build_container_and_test:
    name: Pytest in Pipenv
    # runs on the latest Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: x86_64-apple-darwin
          - os: ubuntu-latest
            TARGET: armv7-unknown-linux-musleabihf
          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-musl
    # runs within your Docker container
    container:
      image: docker://mattforge/python-fibonacci-actions:master
    # checkout your code from your repository
    # and runs pytest in your pipenv environment
    steps:
      - name: Wait for image to be pushed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Push Docker image to Docker Hub'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5
      - uses: actions/checkout@v2
      - name: Test with pytest
        run: |
          pipenv install
          pipenv run pytest fibonacci.py
