# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
      - uses: docker/login-action@v1.12.0
      - with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: mattforge/python-fibonacci-actions

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  build_container_and_test:
    name: Pytest in Pipenv
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest
    # runs within your Docker container
    container:
      image: docker://mattforge/python-fibonacci-actions:latest
    # checkout your code from your repository
    # and runs pytest in your pipenv environment
    steps:
      - uses: actions/checkout@v2
      - name: Test with pytest
        run: |
          pipenv run pytest fibonacci.py
